endpoints:
  - name: swagger
    url: http://localhost:8080/actuator/health
    method: GET
    timeout: 5
    expectation:
      - type: HTTP_STATUS
        status_range: 200-300
        incident: MAJOR
      - type: LATENCY
        threshold: 2
      - type: JSON_CHECK
        field: 'components.messagingService.details.RealService'
        value: 'UP'
        is_independent: true
        component_id: 1
      - type: JSON_CHECK
        field: 'components.authentixService.details.RealService'
        value: 'UP'
        is_independent: true
        component_id: 2
      - type: JSON_CHECK
        field: 'status.code'
        value: 'UP'
    allowed_fails: 0
    frequency: 30
    component_id: 3
    #metric_id: 1
    action:
      - CREATE_INCIDENT
      - UPDATE_STATUS
    public_incidents: true
    latency_unit: ms
cachet:
  api_url: http://localhost:8010/api/v1
  token:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_TOKEN
    - type: TOKEN
      value: zXNU0UCTUt9v1g1VmNIK
